"""
Pulpit — Ingestion Lambda

Fetches 2026+ sermon transcripts from Atlanta Bethel Church YouTube channel.
Uses YouTube Data API v3 directly via requests (no Google client library needed).
youtube-transcript-api pulls free captions — no compiled dependencies.
"""

import json
import os
import re
import boto3
import requests
from datetime import datetime, timezone

s3  = boto3.client("s3")
ssm = boto3.client("ssm")

BUCKET     = os.environ["TRANSCRIPT_BUCKET"]
CHANNEL_ID = os.environ["YOUTUBE_CHANNEL_ID"]
SSM_KEY    = os.environ["SSM_PARAMETER_NAME"]


def get_youtube_api_key():
    """Fetch API key from SSM at runtime — never stored in code or env vars."""
    response = ssm.get_parameter(Name=SSM_KEY, WithDecryption=True)
    return response["Parameter"]["Value"]


def lambda_handler(event, context):
    api_key    = get_youtube_api_key()
    new_videos = get_new_videos(api_key)

    ingested = []
    skipped  = []

    for video in new_videos:
        video_id = video["id"]

        # Only ingest 2026+ sermons — cost control for pilot
        published_year = int(video["published_at"][:4])
        if published_year < 2026:
            skipped.append(video_id)
            continue

        if transcript_exists(video_id):
            skipped.append(video_id)
            continue

        transcript = fetch_transcript(video_id)
        if not transcript:
            skipped.append(video_id)
            continue

        sermon = build_sermon_record(video, transcript)
        store_transcript(sermon)
        ingested.append(video_id)
        print(f"Ingested: {sermon['title']} ({sermon['date']})")

    print(f"Done — ingested: {len(ingested)}, skipped: {len(skipped)}")
    return {"ingested": ingested, "skipped": skipped}


def get_new_videos(api_key, max_results=20):
    """
    Fetch completed live streams from the channel.
    Live streams always have auto-captions generated by YouTube
    (real-time transcription saved after stream ends).
    Regular uploaded videos often have captions disabled.
    eventType=completed filters to finished live streams only.
    """
    url = "https://www.googleapis.com/youtube/v3/search"
    params = {
        "part":       "snippet",
        "channelId":  CHANNEL_ID,
        "order":      "date",
        "type":       "video",
        "eventType":  "completed",
        "maxResults": max_results,
        "key":        api_key
    }

    resp = requests.get(url, params=params, timeout=10)
    resp.raise_for_status()
    data = resp.json()

    return [
        {
            "id":           item["id"]["videoId"],
            "title":        item["snippet"]["title"],
            "description":  item["snippet"]["description"],
            "published_at": item["snippet"]["publishedAt"],
        }
        for item in data.get("items", [])
        if item.get("id", {}).get("videoId")
    ]


def fetch_transcript(video_id):
    """
    Pull free YouTube captions — no API key needed.
    youtube-transcript-api v1.x uses instance-based API.
    Atlanta Bethel sermons are Korean — fetches Korean auto-generated captions.
    Falls back to any available language if Korean not found.
    """
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
        api = YouTubeTranscriptApi()
        transcript_list = api.list(video_id)

        # Try Korean first (Atlanta Bethel is a Korean church)
        # Fall back to English, then any available language
        try:
            transcript = transcript_list.find_transcript(["ko", "en"])
        except Exception:
            # Take whatever is available
            transcript = next(iter(transcript_list))

        segments = transcript.fetch()
        return " ".join([seg.text for seg in segments])
    except Exception as e:
        print(f"No transcript for {video_id}: {e}")
        return None


def extract_scripture_references(text):
    pattern = (
        r'\b(?:Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|'
        r'(?:1|2)\s*Samuel|(?:1|2)\s*Kings|(?:1|2)\s*Chronicles|Ezra|Nehemiah|'
        r'Esther|Job|Psalms?|Proverbs|Ecclesiastes|Isaiah|Jeremiah|Lamentations|'
        r'Ezekiel|Daniel|Hosea|Joel|Amos|Obadiah|Jonah|Micah|Nahum|Habakkuk|'
        r'Zephaniah|Haggai|Zechariah|Malachi|Matthew|Mark|Luke|John|Acts|Romans|'
        r'(?:1|2)\s*Corinthians|Galatians|Ephesians|Philippians|Colossians|'
        r'(?:1|2)\s*Thessalonians|(?:1|2)\s*Timothy|Titus|Philemon|Hebrews|'
        r'James|(?:1|2)\s*Peter|(?:1|2|3)\s*John|Jude|Revelation)'
        r'\s+\d+(?::\d+(?:-\d+)?)?\b'
    )
    return list(set(re.findall(pattern, text, re.IGNORECASE)))


def build_sermon_record(video, transcript):
    description = video.get("description", "")
    return {
        "sermon_id":            video["id"],
        "title":                video["title"],
        "date":                 video["published_at"][:10],
        "youtube_url":          f"https://youtube.com/watch?v={video['id']}",
        "scripture_references": extract_scripture_references(
            video["title"] + " " + description
        ),
        "description":          description[:500],
        "transcript":           transcript,
        "ingested_at":          datetime.now(timezone.utc).isoformat()
    }


def transcript_exists(video_id):
    try:
        s3.head_object(Bucket=BUCKET, Key=f"transcripts/{video_id}.json")
        return True
    except Exception:
        return False


def store_transcript(sermon):
    key = f"transcripts/{sermon['date'][:4]}/{sermon['sermon_id']}.json"
    s3.put_object(
        Bucket=BUCKET,
        Key=key,
        Body=json.dumps(sermon, ensure_ascii=False),
        ContentType="application/json"
    )
